spring:
  application:
    name: TPO_12
  h2:
    console:
      path: /my-h2-console
  datasource:
    url: jdbc:h2:mem:books
    username: s28113
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  sql:
    init:
      data-locations: classpath:sql-data/*.sql
  security:
    user:
      name: admin
      password: admin